### ISSUE TITLE
Update to v1.2.0

### ISSUE THREAD

**Issue by tobru** [projectsyn/component-csi-cloudscale#5]
## Context

A new version of cloudscale.ch CSI has been released: https://github.com/cloudscale-ch/csi-cloudscale/blob/master/CHANGELOG.md#v120---20200825. Update the component to this version.

## Alternatives

Not upgrading is not an option.

**Comment by mhutter** [comment]
Required to support multiple clusters in different locations in the same cloudscale.ch account

**Comment by simu** [comment]
v1.0.0 is on v1.3.1. Closing this issue.
